ALTER TABLE seasonal_specials
    ADD COLUMN header_text VARCHAR(255) NOT NULL,
    ADD COLUMN description TEXT NULL,
    ADD COLUMN image_path VARCHAR(500) NULL,
    ADD COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
