ALTER TABLE inventory
    ADD COLUMN item_name VARCHAR(255) NOT NULL,
    ADD COLUMN abv DECIMAL(4,2) NULL,
    ADD COLUMN price DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    ADD COLUMN description TEXT NULL,
    ADD COLUMN image_path VARCHAR(500) NULL,
    ADD COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
