ALTER TABLE map_locations
    ADD COLUMN name VARCHAR(255) NOT NULL,
    ADD COLUMN address VARCHAR(500) NOT NULL,
    ADD COLUMN beers_sold TEXT NULL,
    ADD COLUMN latitude DECIMAL(10,8) NULL,
    ADD COLUMN longitude DECIMAL(11,8) NULL,
    ADD COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
