ALTER TABLE users
    ADD COLUMN email VARCHAR(255) NOT NULL,
    ADD COLUMN password_hash VARCHAR(255) NOT NULL,
    ADD COLUMN first_name VARCHAR(100) NULL,
    ADD COLUMN last_name VARCHAR(100) NULL,
    ADD COLUMN role VARCHAR(50) NOT NULL DEFAULT 'admin',
    ADD COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ADD CONSTRAINT uq_users_email UNIQUE (email);
